language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install coverage codecov 
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install enum34 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install enum34 ; fi
# command to run tests
script:
  - coverage run -m unittest discover -s src
after_success:
  - codecov	
